version: '3.8'

services:
  db:
    image: postgres:latest
    hostname: ${POSTGRES_HOST}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

  app:
    image: odoo:latest
    hostname: odoo_app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web"]
      interval: 30s
      timeout: 10s
      retries: 5
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/odoo.conf:/odoo/odoo.conf
    networks:
      - internal_network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    hostname: odoo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/cert/nginx-selfsigned.crt:/etc/ssl/nginx/server.crt
      - ./config/cert/nginx-selfsigned.key:/etc/ssl/nginx/server.key
      - nginx_logs:/var/log/nginx
    networks:
      - internal_network
    depends_on:
      - app

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-volumes/postgres_data

  nginx_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-volumes/nginx_logs

networks:
  internal_network:
    driver: bridge